version: '3'
services:
  db:
    container_name: dnd-mysql
    image: mysql
    restart: always
    volumes:
      - C:\Users\matwe\docker\dnd-mysql:/var/lib/mysql
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'dnd'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306